#!/usr/bin/env python2

import os
import os.path
import argparse
import time
from termcolor import colored

from analizer import analize


parser = argparse.ArgumentParser(description='Analize media files for ' +
                                'detecting pornography.')

parser.add_argument('files', metavar='file', type=str, nargs='+',
                    help='File to analize.')

parser.add_argument('-P', action='store', default=15,
                    help='The percentage of skin to determinate a positive.')

parser.add_argument('-O', action='store_const', const=True, default=False,
                    help='Show only positive file')

parser.add_argument('-F', action='store_const', const=True, default=False,
                    help='The output file.')

parser.add_argument('-R', action='store_const', const=True, default=False,
                    help='Analize recursively.')

parser.add_argument('-L', action='store_const', const=True, default=False,
                    help='Follow symbolic links.')

args = parser.parse_args()


def print_result(path, result):
    if result:
        if args.F:
            out_file.write(path+'\n')
        else:
            print path + ": " + colored(';D', 'green', attrs=['bold'])
    elif not args.O:
        print path + ": " + colored(':(', 'red')

if args.F:
    try:
        out_file = open("Pija Result "+ time.strftime("%c")+".txt","w")
    except IOError:
        print "Error writin output file! Abort!"
        exit()

for file_ in args.files:

    file_ = os.path.expanduser(file_)

    if not os.path.exists(file_):
        print file_ + " doesn't exist."
        continue

    if not os.access(file_, os.R_OK):
        print file_ + " can't be read."
        contin  
    if os.path.isdir(file_) and not args.R:
        print file_ + " is a folder, see -R option."
        continue

    if os.path.isdir(file_):
        for (dirpath, _, filenames) in os.walk(file_, True, None, args.L):
            for name in filenames:
                path = dirpath + "/" + name
                print_result(path, analize(path))
    else:
        print_result(file_, analize(file_))

if args.F:
    out_file.close()
